apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-grafana-admin-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-aws
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-grafana-admin-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: devops-stack-grafana-admin-credentials
