# When the secret to be created contains sensitive information, it is necessary to use the ExternalSecret resource to 
# create it. Otherwise, the secret only contains a generic configuration and is directly created using the 
# template `secret_metrics_storage.yaml`.
---
{{- if and .Values.secrets_names.kube_prometheus_stack.metrics_storage .Values.metrics_storage  -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-metrics-storage-configuration
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secrets_names.cluster_secret_store }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}-metrics-storage-configuration
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        thanos.yaml: |
          type: {{ .Values.metrics_storage.type }}
          config:
            access_key: {{ `{{ .access_key }}` }}
            secret_key: {{ `{{ .secret_key }}` }}
            {{- range $key, $value := .Values.metrics_storage.config }}
            {{ $key }}: {{ $value }}
            {{- end }}
  dataFrom:
  - extract:
      key: {{ .Values.secrets_names.kube_prometheus_stack.metrics_storage }}
{{- end -}}
