# When the secret to be created contains only a generic configuration (p.e, when using an IAM identity in EKS clusters),
# it is directly created using this template, otherwise the template `externalsercret_metrics_storage.yaml` is used.
---
{{- if and (not .Values.secrets_names.kube_prometheus_stack.metrics_storage) .Values.metrics_storage  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-metrics-storage-configuration
  namespace: {{ .Release.Namespace }}
stringData:
  thanos.yaml: |
    type: {{ .Values.metrics_storage.type }}
    config:
      {{- range $key, $value := .Values.metrics_storage.config }}
      {{ $key }}: {{ $value }}
      {{- end }}
{{- end -}}
